[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -rfbport 5900 -localhost -nopw -forever -shared -repeat -xkb -noxdamage -threads -quiet
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisord/x11vnc
stderr_logfile=/var/log/supervisord/x11vnc
stopasgroup=true
killasgroup=true
