[program:xvnc]
command=/usr/bin/Xvnc :1 -geometry 1920x1080 -depth 24 -rfbport 5900 -localhost=1 -SecurityTypes None -AlwaysShared=1 -Log *:stderr:100
autostart=false
autorestart=true
startsecs=2
stdout_logfile=/var/log/supervisord/xvnc
redirect_stderr=true
